#!/bin/bash

# Coolify Deployment Script for Estrogen.Email
# This script helps prepare the application for Coolify deployment

echo "🏳️‍⚧️ Preparing Estrogen.Email for Coolify Deployment"
echo "===================================================="

# Check if we're in the right directory
if [ ! -f "docker-compose.yml" ]; then
    echo "❌ docker-compose.yml not found. Please run this script from the project root."
    exit 1
fi

echo "✅ Project structure verified"

# Create required directories
mkdir -p logs
echo "✅ Created logs directory"

# Validate Docker configuration
echo "🔍 Validating Docker configuration..."
if docker-compose config &> /dev/null; then
    echo "✅ Docker Compose configuration is valid"
else
    echo "❌ Docker Compose configuration has errors"
    docker-compose config
    exit 1
fi

# Check if all required files exist
required_files=(
    "docker-compose.yml"
    "mail-server-api/Dockerfile"
    "mail-server-frontend/Dockerfile"
    "schema_emails.sql"
    ".env.example"
)

for file in "${required_files[@]}"; do
    if [ -f "$file" ]; then
        echo "✅ $file exists"
    else
        echo "❌ $file is missing"
        exit 1
    fi
done

echo ""
echo "🎉 Ready for Coolify deployment!"
echo "================================="
echo ""
echo "📋 Coolify Setup Checklist:"
echo "□ 1. Import this repository in Coolify"
echo "□ 2. Set the following environment variables:"
echo "     - JWT_SECRET (32+ random characters)"
echo "     - POSTGRES_PASSWORD (auto-generated)"
echo "     - SMTP_HOST, SMTP_USER, SMTP_PASS"
echo "     - CORS_ORIGIN (your domain)"
echo "     - REACT_APP_API_URL (your API domain)"
echo "□ 3. Configure DNS records:"
echo "     - A records for your domains"
echo "     - MX records for email routing"
echo "     - SPF/DKIM/DMARC for deliverability"
echo "□ 4. Deploy the application"
echo "□ 5. Test email creation and forwarding"
echo ""
echo "🔧 Environment Variables Template:"
echo "JWT_SECRET=\$(openssl rand -base64 32)"
echo "POSTGRES_PASSWORD=\$(auto-generated by Coolify)"
echo "SMTP_HOST=smtp.gmail.com"
echo "SMTP_USER=your-email@gmail.com"
echo "SMTP_PASS=your-app-password"
echo "CORS_ORIGIN=https://your-domain.com"
echo "REACT_APP_API_URL=https://api.your-domain.com"
echo ""
echo "📧 DNS Configuration Example:"
echo "your-domain.com        A     YOUR_SERVER_IP"
echo "api.your-domain.com    A     YOUR_SERVER_IP"
echo "your-domain.com        MX    10 mail.your-domain.com"
echo "your-domain.com        TXT   \"v=spf1 ip4:YOUR_SERVER_IP -all\""
echo ""
echo "🚀 Ready to deploy with Coolify!"
