version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 5000
      
      # Database (using external PostgreSQL)
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-emailmanager}
      DB_USER: ${DB_USER:-emailuser}
      DB_PASSWORD: ${DB_PASSWORD}
      
      # JWT
      JWT_SECRET: ${JWT_SECRET}
      
      # Email/SMTP Settings
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_SECURE: ${SMTP_SECURE:-false}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: ${SMTP_FROM:-noreply@estrogen.email}
      
      # App Settings
      ALLOWED_DOMAINS: ${ALLOWED_DOMAINS:-estrogen.email,blahaj.email}
      CORS_ORIGIN: ${CORS_ORIGIN}
      
    ports:
      - "5000:5000"
    volumes:
      - app_logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  app_logs:
    driver: local
